services:
  tunequest-card-generator:
    build:
      context: .
      dockerfile: Dockerfile            # see Dockerfile below
    container_name: tunequest-card-generator
    ports:
      - "3004:80"                       # container:80 → host:3004
    restart: always
    depends_on:
      - tunequest-backend
  tunequest-backend:
    build:
      context: .
      dockerfile: Backend.Dockerfile
    container_name: tunequest-backend
    ports:
      - "3005:3005" # expose backend port
    restart: always